USE [MRGFE]
GO

/****** Object:  StoredProcedure [dbo].[procMRGFEEmisorActualizar]    Script Date: 27/02/2023 06:34:45 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[procMRGFEEmisorActualizar]
	@EMISORRFC varchar(50) = '',
	@EMISORRAZSOCIAL varchar(500) = '',
	@EMISORESTATUS varchar(50) = '',
	@EMISORREGFISCAL varchar(50) = '',
	@EMISORCORREO varchar(100) = '',
	@EMISORLOGOURL varchar(500) = '',
	@EMISORCODPOSTAL varchar(20) = '',
	@EMISORMUNICIPIO varchar(100) = '',
	@EMISORESTADO varchar(50) = '',
	@EMISORCOLONIA varchar(100) = '',
	@EMISORCALLE varchar(100) = '',
	@EMISORNOEXTERIOR varchar(30) = '',
	@EMISORNOINTERIOR varchar(30) = '',
	@EMISORFOLIOINIC varchar(50) = ''
AS
	/* jme 20230209. Actualiza un Emisor derivado de los parametros del sp*/
	UPDATE tblMRGFEEmisor
	SET EMISORRFC = @EMISORRFC
		,EMISORRAZSOCIAL = @EMISORRAZSOCIAL
		,EMISORESTATUS = @EMISORESTATUS
		,EMISORREGFISCAL = @EMISORREGFISCAL
		,EMISORCORREO = @EMISORCORREO
		,EMISORLOGOURL = @EMISORLOGOURL
		,EMISORCODPOSTAL = @EMISORCODPOSTAL
		,EMISORMUNICIPIO = @EMISORMUNICIPIO
		,EMISORESTADO = @EMISORESTADO
		,EMISORCOLONIA = @EMISORCOLONIA
		,EMISORCALLE = @EMISORCALLE
		,EMISORNOEXTERIOR = @EMISORNOEXTERIOR
		,EMISORNOINTERIOR = @EMISORNOINTERIOR
		,EMISORFOLIOINIC = @EMISORFOLIOINIC
	WHERE EMISORRFC = @EMISORRFC;
GO


