USE [MRGFE]
GO

/****** Object:  StoredProcedure [dbo].[procMRGFEEmisorRecuperar]    Script Date: 27/02/2023 06:32:29 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[procMRGFEEmisorRecuperar] 
	@accion int = 0,
	@EMISORRFC varchar(50) = ''
AS
	/* jme 20230215. Consultar los Emisores registrados*/
	IF (@accion = 1)
		SELECT
			tEM.EMISORRFC,
			tEM.EMISORRAZSOCIAL,
			tEM.EMISORESTATUS,
			tEM.EMISORREGFISCAL,
			tEM.EMISORCORREO,
			tEM.EMISORLOGOURL,
			tEM.EMISORCODPOSTAL,
			tEM.EMISORMUNICIPIO,
			tEM.EMISORESTADO,
			tEM.EMISORCOLONIA,
			tEM.EMISORCALLE,
			tEM.EMISORNOEXTERIOR,
			tEM.EMISORNOINTERIOR,
			tEM.EMISORFOLIOINIC
		FROM tblMRGFEEmisor tEM;
	/* jme 20230209. Consultar los emisores con el RFC del parametro de busqueda*/
	IF (@accion = 2)
		SELECT 
			tEM.EMISORRFC,
			tEM.EMISORRAZSOCIAL,
			tEM.EMISORESTATUS,
			tEM.EMISORREGFISCAL,
			tEM.EMISORCORREO,
			tEM.EMISORLOGOURL,
			tEM.EMISORCODPOSTAL,
			tEM.EMISORMUNICIPIO,
			tEM.EMISORESTADO,
			tEM.EMISORCOLONIA,
			tEM.EMISORCALLE,
			tEM.EMISORNOEXTERIOR,
			tEM.EMISORNOINTERIOR,
			tEM.EMISORFOLIOINIC
		FROM tblMRGFEEmisor tEM
		WHERE tEM.EMISORRFC = @EMISORRFC;
GO


