USE [MRGFE]
GO

/****** Object:  StoredProcedure [dbo].[procMRGFECamposFacturamaActualizar]    Script Date: 27/02/2023 06:39:43 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[procMRGFECamposFacturamaActualizar] 
	@CAMPOSFAID varchar(50) = '',
	@CAMPOSFACAMPO varchar(100) = '',
	@CAMPOSFAETIQUETA varchar(500) = '',
	@CAMPOSFATIPODATO varchar(100) = '',
	@CAMPOSFAARREGLO1 bit = 0,
	@CAMPOSFAVERSION varchar(100) = '',
	@CAMPOSFAOBLIGA1 bit = 0
AS
	/* jme 20230209. Actualiza un Campo Facturama derivado de los parametros del sp*/
	UPDATE tblMRGFECamposFacturama
	SET CAMPOSFAID = @CAMPOSFAID
		,CAMPOSFACAMPO = @CAMPOSFACAMPO
		,CAMPOSFAETIQUETA = @CAMPOSFAETIQUETA
		,CAMPOSFATIPODATO = @CAMPOSFATIPODATO
		,CAMPOSFAARREGLO1 = @CAMPOSFAARREGLO1
		,CAMPOSFAVERSION = @CAMPOSFAVERSION
		,CAMPOSFAOBLIGA1 = @CAMPOSFAOBLIGA1
	WHERE CAMPOSFAID = @CAMPOSFAID;
GO