USE [MRGFE]
GO

/****** Object:  StoredProcedure [dbo].[procMRGFECamposMirageActualizar]    Script Date: 27/02/2023 06:46:56 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[procMRGFECamposMirageActualizar] 
	@CAMPOSMIID varchar(50) = '',
	@CAMPOSMICAMPO varchar(100) = '',
	@CAMPOSMIETIQUETA varchar(500) = '',
	@CAMPOSMITIPODATO varchar(100) = '',
	@CAMPOSMIARREGLO1 bit = 0,
	@CAMPOSMIVERSION varchar(100) = '',
	@CAMPOSMIOBLIGA1 bit = 0
AS
	/* jme 20230209. Actualiza un Campo Mirage derivado de los parametros del sp*/
	UPDATE tblMRGFECamposMirage
	SET CAMPOSMIID = @CAMPOSMIID
		,CAMPOSMICAMPO = @CAMPOSMICAMPO
		,CAMPOSMIETIQUETA = @CAMPOSMIETIQUETA
		,CAMPOSMITIPODATO = @CAMPOSMITIPODATO
		,CAMPOSMIARREGLO1 = @CAMPOSMIARREGLO1
		,CAMPOSMIVERSION = @CAMPOSMIVERSION
		,CAMPOSMIOBLIGA1 = @CAMPOSMIOBLIGA1
	WHERE CAMPOSMIID = @CAMPOSMIID;
GO
