USE [MRGFE]
GO

/****** Object:  StoredProcedure [dbo].[procMRGFECFDIsRecuperacionCFDIs]    Script Date: 27/02/2023 06:24:47 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[procMRGFECFDIsRecuperacionCFDIs]
	@accion int = 0,
	@CFDIID varchar(50) = '' ,
	@CFDIFOLIOFISCAL varchar(50) = '', 
	@CFDIFECHAINICIO datetime = '19000101',
	@CFDIFECHAFIN datetime = '19000101',
	@CFDIRFCEMISOR varchar(50) = '',
	@CFDIRFCRECEPTOR varchar(50) = ''
AS
/* jme 20230215. Consultar los CFDIs registrados*/
	IF (@accion = 1)
		SELECT
			tCF.CFDIID,
			tCF.CFDIFOLIOFISCAL,
			tCF.CFDISERIE,
			tCF.CFDIRSOCEMISOR,
			tCF.CFDIRFCEMISOR,
			tCF.CFDIRSOCRECEPTOR,
			tCF.CFDIRFCRECEPTOR,
			tCF.CFDIFECHA,
			tCF.CFDITOTAL,
			tCF.CFDIEMAIL,
			tCF.CFDIESACTIVO,
			tCF.CFDIEMAILENVIADO,
			tCF.CFDIPDF,
			tCF.CFDIXML,
			tCF.CFDIPROCESADO1PDF,
			tCF.CFDIPROCESADO1XML,
			tCF.CFDIURLPDF,
			tCF.CFDIURLXML,
			tCF.CFDIFECHAPROCESADOPDF,
			tCF.CFDIFECHAPROCESADOXML
		FROM tblMRGFECFDIs tCF;
	/* jme 20230215. Consultar los CFDIs con el id del parametro de busqueda*/
	IF (@accion = 2)
		SELECT 
			tCF.CFDIID,
			tCF.CFDIFOLIOFISCAL,
			tCF.CFDISERIE,
			tCF.CFDIRSOCEMISOR,
			tCF.CFDIRFCEMISOR,
			tCF.CFDIRSOCRECEPTOR,
			tCF.CFDIRFCEMISOR,
			tCF.CFDIRFCRECEPTOR,
			tCF.CFDIFECHA,
			tCF.CFDITOTAL,
			tCF.CFDIEMAIL,
			tCF.CFDIESACTIVO,
			tCF.CFDIEMAILENVIADO,
			tCF.CFDIPDF,
			tCF.CFDIXML,
			tCF.CFDIPROCESADO1PDF,
			tCF.CFDIPROCESADO1XML,
			tCF.CFDIURLPDF,
			tCF.CFDIURLXML,
			tCF.CFDIFECHAPROCESADOPDF,
			tCF.CFDIFECHAPROCESADOXML
		FROM tblMRGFECFDIs tCF
		WHERE tCF.CFDIID = @CFDIID;
	/* jme 20230215. Consultar los CFDIs por el folio fiscal del parametro de busqueda*/
	IF (@accion = 3)
		SELECT 
			tCF.CFDIID,
			tCF.CFDIFOLIOFISCAL,
			tCF.CFDISERIE,
			tCF.CFDIRSOCEMISOR,
			tCF.CFDIRFCEMISOR,
			tCF.CFDIRSOCRECEPTOR,
			tCF.CFDIRFCEMISOR,
			tCF.CFDIRFCRECEPTOR,
			tCF.CFDIFECHA,
			tCF.CFDITOTAL,
			tCF.CFDIEMAIL,
			tCF.CFDIESACTIVO,
			tCF.CFDIEMAILENVIADO,
			tCF.CFDIPDF,
			tCF.CFDIXML,
			tCF.CFDIPROCESADO1PDF,
			tCF.CFDIPROCESADO1XML,
			tCF.CFDIURLPDF,
			tCF.CFDIURLXML,
			tCF.CFDIFECHAPROCESADOPDF,
			tCF.CFDIFECHAPROCESADOXML
		FROM tblMRGFECFDIs tCF 
		WHERE CFDIFOLIOFISCAL = @CFDIFOLIOFISCAL;
	/* jme 20230215. Consultar los CFDis por rfc de emisor, rfc de receptor, ambos o por rango de fechas de los parametros de busqueda*/
	IF (@accion = 4)
		IF( @CFDIRFCRECEPTOR != '' 
			and @CFDIRFCEMISOR != '')
			   SELECT 
				tCF.CFDIID,
				tCF.CFDIFOLIOFISCAL,
				tCF.CFDISERIE,
				tCF.CFDIRSOCEMISOR,
				tCF.CFDIRFCEMISOR,
				tCF.CFDIRSOCRECEPTOR,
				tCF.CFDIRFCEMISOR,
				tCF.CFDIRFCRECEPTOR,
				tCF.CFDIFECHA,
				tCF.CFDITOTAL,
				tCF.CFDIEMAIL,
				tCF.CFDIESACTIVO,
				tCF.CFDIEMAILENVIADO,
				tCF.CFDIPDF,
				tCF.CFDIXML,
				tCF.CFDIPROCESADO1PDF,
				tCF.CFDIPROCESADO1XML,
				tCF.CFDIURLPDF,
				tCF.CFDIURLXML,
				tCF.CFDIFECHAPROCESADOPDF,
				tCF.CFDIFECHAPROCESADOXML
			FROM tblMRGFECFDIs tCF 
			   WHERE convert(varchar(8),CFDIFECHA,112) >= convert(varchar(8),@CFDIFECHAINICIO,112)
					AND convert(varchar(8),CFDIFECHA,112) <= convert(varchar(8),@CFDIFECHAFIN,112)
					and CFDIRFCRECEPTOR = @CFDIRFCRECEPTOR
					and CFDIRFCEMISOR = @CFDIRFCEMISOR;
		IF ( @CFDIRFCRECEPTOR != '' )
			   SELECT 
				tCF.CFDIID,
				tCF.CFDIFOLIOFISCAL,
				tCF.CFDISERIE,
				tCF.CFDIRSOCEMISOR,
				tCF.CFDIRFCEMISOR,
				tCF.CFDIRSOCRECEPTOR,
				tCF.CFDIRFCEMISOR,
				tCF.CFDIRFCRECEPTOR,
				tCF.CFDIFECHA,
				tCF.CFDITOTAL,
				tCF.CFDIEMAIL,
				tCF.CFDIESACTIVO,
				tCF.CFDIEMAILENVIADO,
				tCF.CFDIPDF,
				tCF.CFDIXML,
				tCF.CFDIPROCESADO1PDF,
				tCF.CFDIPROCESADO1XML,
				tCF.CFDIURLPDF,
				tCF.CFDIURLXML,
				tCF.CFDIFECHAPROCESADOPDF,
				tCF.CFDIFECHAPROCESADOXML
			FROM tblMRGFECFDIs tCF 
			   WHERE convert(varchar(8),CFDIFECHA,112) >= convert(varchar(8),@CFDIFECHAINICIO,112)
					AND convert(varchar(8),CFDIFECHA,112) <= convert(varchar(8),@CFDIFECHAFIN,112)
					and CFDIRFCRECEPTOR = @CFDIRFCRECEPTOR;
		IF ( @CFDIRFCEMISOR != '' )
			   SELECT 
				tCF.CFDIID,
				tCF.CFDIFOLIOFISCAL,
				tCF.CFDISERIE,
				tCF.CFDIRSOCEMISOR,
				tCF.CFDIRFCEMISOR,
				tCF.CFDIRSOCRECEPTOR,
				tCF.CFDIRFCEMISOR,
				tCF.CFDIRFCRECEPTOR,
				tCF.CFDIFECHA,
				tCF.CFDITOTAL,
				tCF.CFDIEMAIL,
				tCF.CFDIESACTIVO,
				tCF.CFDIEMAILENVIADO,
				tCF.CFDIPDF,
				tCF.CFDIXML,
				tCF.CFDIPROCESADO1PDF,
				tCF.CFDIPROCESADO1XML,
				tCF.CFDIURLPDF,
				tCF.CFDIURLXML,
				tCF.CFDIFECHAPROCESADOPDF,
				tCF.CFDIFECHAPROCESADOXML
			FROM tblMRGFECFDIs tCF 
			   WHERE convert(varchar(8),CFDIFECHA,112) >= convert(varchar(8),@CFDIFECHAINICIO,112)
					AND convert(varchar(8),CFDIFECHA,112) <= convert(varchar(8),@CFDIFECHAFIN,112)
					AND CFDIRFCEMISOR = @CFDIRFCEMISOR;
		IF( @CFDIRFCRECEPTOR = '' 
			and @CFDIRFCEMISOR = '')
			   SELECT 
				tCF.CFDIID,
				tCF.CFDIFOLIOFISCAL,
				tCF.CFDISERIE,
				tCF.CFDIRSOCEMISOR,
				tCF.CFDIRFCEMISOR,
				tCF.CFDIRSOCRECEPTOR,
				tCF.CFDIRFCEMISOR,
				tCF.CFDIRFCRECEPTOR,
				tCF.CFDIFECHA,
				tCF.CFDITOTAL,
				tCF.CFDIEMAIL,
				tCF.CFDIESACTIVO,
				tCF.CFDIEMAILENVIADO,
				tCF.CFDIPDF,
				tCF.CFDIXML,
				tCF.CFDIPROCESADO1PDF,
				tCF.CFDIPROCESADO1XML,
				tCF.CFDIURLPDF,
				tCF.CFDIURLXML,
				tCF.CFDIFECHAPROCESADOPDF,
				tCF.CFDIFECHAPROCESADOXML
			FROM tblMRGFECFDIs tCF 
			   WHERE convert(varchar(8),CFDIFECHA,112) >= convert(varchar(8),@CFDIFECHAINICIO,112)
					AND convert(varchar(8),CFDIFECHA,112) <= convert(varchar(8),@CFDIFECHAFIN,112);
GO


