USE [MRGFE]
GO

/****** Object:  StoredProcedure [dbo].[procMRGFEEmisorEliminar]    Script Date: 27/02/2023 06:35:34 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[procMRGFEEmisorEliminar] 
	@EMISORRFC varchar(50) = ''
AS
	/* jme 20230209. Elimina un Emisor derivado de los parametros del sp*/
	DELETE tEM
	FROM tblMRGFEEmisor tEM
	WHERE 
		NOT EXISTS (
			SELECT 
				tCF.CFDIID,
				tCF.CFDIFOLIOFISCAL,
				tCF.CFDISERIE,
				tCF.CFDIRSOCEMISOR,
				tCF.CFDIRFCEMISOR,
				tCF.CFDIRSOCRECEPTOR,
				tCF.CFDIRFCRECEPTOR,
				tCF.CFDIFECHA,
				tCF.CFDITOTAL,
				tCF.CFDIEMAIL,
				tCF.CFDIESACTIVO,
				tCF.CFDIEMAILENVIADO,
				tCF.CFDIPDF,
				tCF.CFDIXML,
				tCF.CFDIPROCESADO1PDF,
				tCF.CFDIPROCESADO1XML,
				tCF.CFDIURLPDF,
				tCF.CFDIURLXML,
				tCF.CFDIFECHAPROCESADOPDF,
				tCF.CFDIFECHAPROCESADOXML
			FROM tblMRGFECFDIs tCF
            WHERE tCF.CFDIRFCEMISOR = @EMISORRFC)
		AND tEM.EMISORRFC = @EMISORRFC;
GO


