USE [MRGFE]
GO

/****** Object:  Table [dbo].[tblMRGFECFDIs]    Script Date: 27/02/2023 06:29:24 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tblMRGFECFDIs](
	[CFDIID] [varchar](50) NOT NULL,
	[CFDIFOLIOFISCAL] [varchar](50) NOT NULL,
	[CFDISERIE] [varchar](50) NOT NULL,
	[CFDIRSOCEMISOR] [varchar](500) NOT NULL,
	[CFDIRFCEMISOR] [varchar](50) NOT NULL,
	[CFDIRSOCRECEPTOR] [varchar](500) NOT NULL,
	[CFDIRFCRECEPTOR] [varchar](50) NOT NULL,
	[CFDIFECHA] [datetime] NOT NULL,
	[CFDITOTAL] [money] NOT NULL,
	[CFDIEMAIL] [varchar](50) NULL,
	[CFDIESACTIVO] [varchar](50) NULL,
	[CFDIEMAILENVIADO] [bit] NULL,
	[CFDIPDF] [varbinary](max) NULL,
	[CFDIXML] [varbinary](max) NULL,
	[CFDIPROCESADO1PDF] [bit] NULL,
	[CFDIPROCESADO1XML] [bit] NULL,
	[CFDIURLPDF] [varchar](8000) NULL,
	[CFDIURLXML] [varchar](8000) NULL,
	[CFDIFECHAPROCESADOPDF] [datetime] NULL,
	[CFDIFECHAPROCESADOXML] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[tblMRGFECFDIs] ADD  DEFAULT ((0)) FOR [CFDIPROCESADO1PDF]
GO

ALTER TABLE [dbo].[tblMRGFECFDIs] ADD  DEFAULT ((0)) FOR [CFDIPROCESADO1XML]
GO


