USE [MRGFE]
GO

/****** Object:  Table [dbo].[tblMRGFECamposMirage]    Script Date: 27/02/2023 06:44:59 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tblMRGFECamposMirage](
	[CAMPOSMIID] [varchar](50) NOT NULL,
	[CAMPOSMICAMPO] [varchar](100) NOT NULL,
	[CAMPOSMIETIQUETA] [varchar](500) NOT NULL,
	[CAMPOSMITIPODATO] [varchar](100) NOT NULL,
	[CAMPOSMIARREGLO1] [bit] NOT NULL,
	[CAMPOSMIVERSION] [varchar](100) NOT NULL,
	[CAMPOSMIOBLIGA1] [bit] NOT NULL,
UNIQUE NONCLUSTERED 
(
	[CAMPOSMIID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, 
	IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


