USE [MRGFE]
GO

/****** Object:  Table [dbo].[tblMRGFEEmisor]    Script Date: 27/02/2023 06:29:42 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tblMRGFEEmisor](
	[EMISORRFC] [varchar](50) NOT NULL,
	[EMISORRAZSOCIAL] [varchar](500) NOT NULL,
	[EMISORESTATUS] [varchar](50) NOT NULL,
	[EMISORREGFISCAL] [varchar](50) NOT NULL,
	[EMISORCORREO] [varchar](100) NOT NULL,
	[EMISORLOGOURL] [varchar](500) NULL,
	[EMISORCODPOSTAL] [varchar](20) NOT NULL,
	[EMISORMUNICIPIO] [varchar](100) NOT NULL,
	[EMISORESTADO] [varchar](50) NOT NULL,
	[EMISORCOLONIA] [varchar](100) NOT NULL,
	[EMISORCALLE] [varchar](100) NOT NULL,
	[EMISORNOEXTERIOR] [varchar](30) NULL,
	[EMISORNOINTERIOR] [varchar](30) NULL,
	[EMISORFOLIOINIC] [varchar](50) NULL,
UNIQUE NONCLUSTERED 
(
	[EMISORRFC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


