USE [MRGFE]
GO

/****** Object:  Table [dbo].[tblMRGFECamposFacturama]    Script Date: 27/02/2023 06:38:25 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tblMRGFECamposFacturama](
	[CAMPOSFAID] [varchar](50) NOT NULL,
	[CAMPOSFACAMPO] [varchar](100) NOT NULL,
	[CAMPOSFAETIQUETA] [varchar](500) NOT NULL,
	[CAMPOSFATIPODATO] [varchar](100) NOT NULL,
	[CAMPOSFAARREGLO1] [bit] NOT NULL,
	[CAMPOSFAVERSION] [varchar](100) NOT NULL,
	[CAMPOSFAOBLIGA1] [bit] NOT NULL,
UNIQUE NONCLUSTERED 
(
	[CAMPOSFAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, 
	ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


